-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AS AI
JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
# 1
# WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%'
# AND
# (AO.SEX_UPON_OUTCOME LIKE 'Neutered%' OR AO.SEX_UPON_OUTCOME LIKE 'Spayed%')
# 2
# WHERE AI.SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female')
#   AND AO.SEX_UPON_OUTCOME IN ('Neutered Male', 'Spayed Female')
# 3
WHERE AI.SEX_UPON_INTAKE != AO.SEX_UPON_OUTCOME
ORDER BY AI.ANIMAL_ID ASC
