SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;

# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM (
#     SELECT *, ROW_NUMBER() OVER # 그룹 내 번호 매김
#     # CATEGORY별 그룹 나눠 가격 기준 내림차순
#     (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# ) AS RANKED
# WHERE RN = 1
# ORDER BY PRICE DESC;
